# Form implementation generated from reading ui file 'RadarPlayerMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RadarPlayerMainWindow(object):
    def setupUi(self, RadarPlayerMainWindow):
        RadarPlayerMainWindow.setObjectName("RadarPlayerMainWindow")
        RadarPlayerMainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=RadarPlayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CarTableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.CarTableView.setGeometry(QtCore.QRect(40, 640, 961, 391))
        self.CarTableView.setObjectName("CarTableView")
        self.ConsoleText = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.ConsoleText.setGeometry(QtCore.QRect(1040, 640, 801, 391))
        self.ConsoleText.setReadOnly(True)
        self.ConsoleText.setObjectName("ConsoleText")
        self.VideoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VideoLabel.setGeometry(QtCore.QRect(40, 80, 960, 540))
        self.VideoLabel.setText("")
        self.VideoLabel.setObjectName("VideoLabel")
        self.MapLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.MapLabel.setGeometry(QtCore.QRect(1050, 180, 700, 375))
        self.MapLabel.setText("")
        self.MapLabel.setObjectName("MapLabel")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 20, 1721, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.NextButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(1800, 120, 101, 41))
        self.NextButton.setObjectName("NextButton")
        self.PauseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PauseButton.setGeometry(QtCore.QRect(1800, 190, 101, 41))
        self.PauseButton.setObjectName("PauseButton")
        self.fpsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.fpsLabel.setGeometry(QtCore.QRect(1050, 90, 121, 41))
        self.fpsLabel.setText("")
        self.fpsLabel.setObjectName("fpsLabel")
        RadarPlayerMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=RadarPlayerMainWindow)
        self.statusbar.setObjectName("statusbar")
        RadarPlayerMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RadarPlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RadarPlayerMainWindow)

    def retranslateUi(self, RadarPlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RadarPlayerMainWindow.setWindowTitle(_translate("RadarPlayerMainWindow", "Radar"))
        self.NextButton.setText(_translate("RadarPlayerMainWindow", "下一帧"))
        self.PauseButton.setText(_translate("RadarPlayerMainWindow", "暂停"))
