# Form implementation generated from reading ui file 'RadarChoiceWidget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RadarChoiceWidget(object):
    def setupUi(self, RadarChoiceWidget):
        RadarChoiceWidget.setObjectName("RadarChoiceWidget")
        RadarChoiceWidget.resize(400, 137)
        self.widget = QtWidgets.QWidget(parent=RadarChoiceWidget)
        self.widget.setGeometry(QtCore.QRect(27, 14, 191, 101))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VideoButton = QtWidgets.QPushButton(parent=self.widget)
        self.VideoButton.setObjectName("VideoButton")
        self.horizontalLayout.addWidget(self.VideoButton)
        self.CameraButton = QtWidgets.QPushButton(parent=self.widget)
        self.CameraButton.setObjectName("CameraButton")
        self.horizontalLayout.addWidget(self.CameraButton)
        self.widget1 = QtWidgets.QWidget(parent=RadarChoiceWidget)
        self.widget1.setGeometry(QtCore.QRect(261, 15, 111, 101))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxTensorrt = QtWidgets.QCheckBox(parent=self.widget1)
        self.checkBoxTensorrt.setObjectName("checkBoxTensorrt")
        self.verticalLayout.addWidget(self.checkBoxTensorrt)
        self.checkBoxSerial = QtWidgets.QCheckBox(parent=self.widget1)
        self.checkBoxSerial.setObjectName("checkBoxSerial")
        self.verticalLayout.addWidget(self.checkBoxSerial)

        self.retranslateUi(RadarChoiceWidget)
        QtCore.QMetaObject.connectSlotsByName(RadarChoiceWidget)

    def retranslateUi(self, RadarChoiceWidget):
        _translate = QtCore.QCoreApplication.translate
        RadarChoiceWidget.setWindowTitle(_translate("RadarChoiceWidget", "Radar"))
        self.VideoButton.setText(_translate("RadarChoiceWidget", "视频"))
        self.CameraButton.setText(_translate("RadarChoiceWidget", "摄像头"))
        self.checkBoxTensorrt.setText(_translate("RadarChoiceWidget", "使用TensorRT"))
        self.checkBoxSerial.setText(_translate("RadarChoiceWidget", "启用串口"))
