# Form implementation generated from reading ui file 'RadarMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RadarMainWindow(object):
    def setupUi(self, RadarMainWindow):
        RadarMainWindow.setObjectName("RadarMainWindow")
        RadarMainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=RadarMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CarTableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.CarTableView.setGeometry(QtCore.QRect(40, 640, 961, 391))
        self.CarTableView.setObjectName("CarTableView")
        self.ConsoleText = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.ConsoleText.setGeometry(QtCore.QRect(1040, 640, 801, 391))
        self.ConsoleText.setReadOnly(True)
        self.ConsoleText.setObjectName("ConsoleText")
        self.VideoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VideoLabel.setGeometry(QtCore.QRect(40, 10, 960, 540))
        self.VideoLabel.setObjectName("VideoLabel")
        self.MapLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.MapLabel.setGeometry(QtCore.QRect(1050, 70, 700, 375))
        self.MapLabel.setObjectName("MapLabel")
        RadarMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=RadarMainWindow)
        self.statusbar.setObjectName("statusbar")
        RadarMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RadarMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RadarMainWindow)

    def retranslateUi(self, RadarMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RadarMainWindow.setWindowTitle(_translate("RadarMainWindow", "Radar"))
        self.VideoLabel.setText(_translate("RadarMainWindow", "TextLabel"))
        self.MapLabel.setText(_translate("RadarMainWindow", "TextLabel"))
