# Form implementation generated from reading ui file 'RadarChoiceWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RadarChoiceWidget(object):
    def setupUi(self, RadarChoiceWidget):
        RadarChoiceWidget.setObjectName("RadarChoiceWidget")
        RadarChoiceWidget.resize(400, 137)
        self.VideoButton = QtWidgets.QPushButton(parent=RadarChoiceWidget)
        self.VideoButton.setGeometry(QtCore.QRect(60, 40, 101, 51))
        self.VideoButton.setObjectName("VideoButton")
        self.CameraButton = QtWidgets.QPushButton(parent=RadarChoiceWidget)
        self.CameraButton.setGeometry(QtCore.QRect(230, 40, 101, 51))
        self.CameraButton.setObjectName("CameraButton")
        self.checkBox = QtWidgets.QCheckBox(parent=RadarChoiceWidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 100, 111, 19))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(RadarChoiceWidget)
        QtCore.QMetaObject.connectSlotsByName(RadarChoiceWidget)

    def retranslateUi(self, RadarChoiceWidget):
        _translate = QtCore.QCoreApplication.translate
        RadarChoiceWidget.setWindowTitle(_translate("RadarChoiceWidget", "Radar"))
        self.VideoButton.setText(_translate("RadarChoiceWidget", "视频"))
        self.CameraButton.setText(_translate("RadarChoiceWidget", "摄像头"))
        self.checkBox.setText(_translate("RadarChoiceWidget", "使用TensorRT"))
